### ISSUE TITLE
Need the folder ./RST/ to run the example!

### ISSUE THREAD

**Issue by zw22zw22** [pku-liang/hasco#1]
I have configured the running environment for HASCO. When I run the code  'python3 testbench/co_resnet_conv.py', It seems the open source does not have directory ./RST/. I need to manually  make those directories.
![image](https://user-images.githubusercontent.com/13556200/119960849-fbe69a80-bfd7-11eb-9f52-c70bc9f71083.png)
Solution:
![image](https://user-images.githubusercontent.com/13556200/119962553-bdea7600-bfd9-11eb-8d02-e6d3e349d03f.png)

**Comment by walkershaw** [comment]
This is a gitignore issue. Have been fixed in config.py.
