### ISSUE TITLE
cannot find valid schedules

### ISSUE THREAD

**Issue by zw22zw22** [pku-liang/hasco#2]
I downloaded the code , and instal as it told, when I was running the script, python3 testbench/co_mobile_gemm.py .
it turned out:
![image](https://user-images.githubusercontent.com/13556200/120274886-1627bd80-c2e3-11eb-9e8c-bfac8929aa8f.png)
How to handle it? Please help!

**Comment by walkershaw** [comment]
@zw22zw22 It seems to be a model issue. **Have you built the Maestro repo correctly?** Can you run the Maestro example? Also, you need to configure the absolute path in config.py.

**Comment by zw22zw22** [comment]
I solved the problem. The reason for this problem is that the value of maestro_home should end with slash '/'，I rewrite the value 
“maestro_home = "~/HASCO/src/maestro" 
with
“maestro_home = "~/HASCO/src/maestro/"

It works 😁!
